name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see and why?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: If you have a specific idea, describe it here.
    validations:
      required: false
